---
version: '3.7'

services:

  tachidesk-docker:
    image: ghcr.io/suwayomi/tachidesk
    container_name: tachidesk-docker
    environment:
      - PUID=0 # ( dont change, require uid to be 1000 )
      - PGID=0 # ( dont change, require gid to be 1000 )
      - TZ=Asia/Shanghai # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - LOGGING=file
    volumes:
      - /<path to folder>/docker-config/tachidesk:/home/suwayomi/.local/share/Tachidesk # edit <path to folder> to your mapped folder
    ports:
      - "4567:4567"
    restart: on-failure:3
